config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'stories/index'
  get 'stories/show', to: 'stories#show'
 # config/routes.rb

resources :stories

  resources :stories do
    resources :comments, only: [:create] do
    member do
      get 'reply', to: 'comments#new_reply'
    end
  end
end
  
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "stories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :child_comments, class_name: 'Comment', foreign_key: 'parent_comment_id', dependent: :destroy
  
  validates :content, presence: true
  validates :user_name, presence: true
end

app/models/story.rb
class Story < ApplicationRecord
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true
    validates :description, presence: true
    validates :user_name, presence: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.build(comment_params)
    @comment.parent_comment_id = params[:comment][:parent_comment_id]
    
    if @comment.save
      redirect_to @story
    else
      redirect_to @story, alert: 'Comment could not be posted.'
    end
  end

  def new_reply
    @story = Story.find(params[:story_id])
    @parent_comment = Comment.find(params[:id])
    @comment = @story.comments.new(parent_comment_id: @parent_comment.id)

    respond_to do |format|
      format.html # renders new_reply.html.erb
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_name, :parent_comment_id)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
    @comment = Comment.new  # For new comment form
   # @comments = @story.comments.includes(:replies)  # Load comments with replies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_comment.html.erb
<li>
  <%= comment.content %>
  <p>Posted by <%= comment.user_name %></p>

  <%= link_to 'Reply', reply_story_comment_path(comment.story, comment) %>

  <ul>
    <%= render partial: 'comments/comment', collection: comment.child_comments, as: :comment %>
  </ul>
</li>

app/views/comments/_form.html.erb
<%= form_with(model: [story, Comment.new], url: story_comments_path(story)) do |form| %>
  <div class="field">
    <%= form.label :user_name, 'Your Name' %>
    <%= form.text_field :user_name %>
  </div><br>

  <div class="field">
    <%= form.label :content, 'Comment' %>
    <%= form.text_area :content %>
  </div><br>

  <%= form.submit 'Post Comment' %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new_reply.html.erb
<h1>Reply to Comment</h1>

<p><%= @parent_comment.content %></p>

<%= form_with(model: [@story, @comment], local: true) do |form| %>
  <%= form.hidden_field :parent_comment_id, value: @parent_comment.id %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div><br>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div><br>

  <div class="actions">
    <%= form.submit 'Post Comment' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storiesapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stories/index.html.erb
<h1>Latest Stories</h1>

<% Story.all.each do |story| %>
  <div class="story">
    <h3><%= link_to story.title, "stories/show?id=#{story.id}", :method => :get %></h3>
    <p><%= truncate(strip_tags(story.description), length: 150) %></p>
    <p><small>Submitted <%= time_ago_in_words(story.created_at) %> ago by <%= name = (story.user_name ? story.user_name : "Anonymous") %></small></p>
    <p class="infotext"> Upvotes: <%= likes = (story.upvotes ? story.upvotes: '0') %> &nbsp &nbsp
    <%= link_to "Comments (#{story.comments.count})", story_path(story) %></p>
    <hr>
  </div>
<% end %>

app/views/stories/show.html.erb
<div class="story">
<h1><%= link_to @story.title, @story.url,target: :_blank %></h1>
<p><%= @story.description %></p>
<p class="infotext"> Upvotes: <%= likes = (@story.upvotes ? @story.upvotes: '0') %> &nbsp &nbsp</p>
<p><small>Submitted <%= time_ago_in_words(@story.created_at) %> ago by <%= name = (@story.user_name ? @story.user_name : "Anonymous") %></small></p>
<%= render partial: 'comments/form', locals: { story: @story } %>
</div>

<% if @story.comments.empty? %>
  <p>No comments yet. Be the first to comment!</p>
<% else %>
<h2>Comments</h2>
  <div id="comments">
    <ul>
      <%= render partial: 'comments/comment', collection: @story.comments.where(parent_comment_id: nil), as: :comment %>
    </ul>
  </div>
<% end %>